[package]
name = "leptos_wgpu"
version = "0.1.0"
edition = "2021"

[lib]
name = "leptos_wgpu"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[dependencies]
winit = { version = "0.29", features = ["rwh_05"] }
env_logger = "0.10"
log = "0.4"
wgpu = "22.0"
